wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    code_path: code/CausalSearch/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1674565374.803088
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.10.8
      5: 0.13.7
      8:
      - 5
criterion:
  desc: null
  value: DAG
data:
  desc: null
  value: null
edge_function:
  desc: null
  value: None
epsilon:
  desc: null
  value: null
goal_test:
  desc: null
  value: Degree One
graph:
  desc: null
  value: ./graphs/cancer.bif
number_of_samples:
  desc: null
  value: 1000000
save_path:
  desc: null
  value: ./results
scoring_function:
  desc: null
  value: BIC
search_method:
  desc: null
  value: DFS
wandb:
  desc: null
  value: true
